### ISSUE TITLE
node package

### ISSUE THREAD

**Issue by lusiakpurnama** [Cloudhuset/Zendesk-Guide-Pusher#1]
Hi,
I made a node package version of your helper. Also added a download function.
https://github.com/lusimail/zendesk-theme-helper
Thanks a lot for the idea :)

**Comment by Herlevsen** [comment]
Hi @lusimail 

I Really like what you have done, and it was actually in our own pipeline. I think it would make sense to not have two separate projects, so i think we should consider merging them together? We have also planned some new features that will be beneficial to a lot of people like: Ability to inject variables into templates files and css, logging in via command line and some other stuff.

What do you think?

**Comment by lusiakpurnama** [comment]
Sure.
How should we merge them?

**Comment by Herlevsen** [comment]
Can you maybe drop me an email at jh@cloudhuset.dk?

**Comment by Herlevsen** [comment]
Merged
